import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Footer from "~/components/Footer";
import Header from "~/components/Header";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-white">
        <Head>
          <meta
            name="google-adsense-account"
            content="ca-pub-1959247734496761"
          />
        </Head>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
